### ISSUE TITLE
Unclear whether "- include: {{some_var}}" makes sense or not

### ISSUE THREAD

**Issue by cbrunnkvist** [cbrunnkvist/ansistrano-symfony-deploy#1]
In its original inception, Ansible's `include` does not support a templated argument because the purpose of the statement is to split tasks into modules, not to support dynamic loading based on `facts`

For example, what if the variable is a fact (=in Ansible speak, a variable that gets declared once-per-host, after connection time, perhaps after `setup` (`gather_facts`) finishes. What file will be included? At which time? Include files have global side effects so the order in which they are invoked (=on behalf of perhaps hundreds of hosts) matter.

How come the `include` method that `ansistrano-deploy` uses today works? Is it purely a fluke? **Should** a role such as `ansistrano-deploy` be using events & handlers, rather than rely in dynamic includes?

**Comment by Zokormazo** [comment]
Now the code uses import_tasks & include_tasks instead of the more generic and confuse include

**Comment by scuben** [comment]
Closed in favour of the use of import/include.
