### ISSUE TITLE
Configurable app/console in order to use the playbook with symfony3 projects

### ISSUE THREAD

**Issue by gtrias** [cbrunnkvist/ansistrano-symfony-deploy#10]
In symfony3 the ``app/console`` has moved to ``bin/console``. This executable path should be configurable via a variable in order to be compatible with symfony3.

**Comment by cbrunnkvist** [comment]
(For future reference: 

Since just-about-everything seems to move around or break between major releases of the framework, I suspect that a more maintainable approach would be to rename the project "ansistrano-symfony2-deploy" and keep all the future changes in a "symfony3-deploy" project.)

**Comment by gtrias** [comment]
I think at the moment the only breaking changes of the major release is the directory structure. So I would just make it configurable in order to be fit in all situations since symfony directory structure can be customized (http://symfony.com/doc/current/cookbook/configuration/override_dir_structure.html).
