### ISSUE TITLE
Project slightly unmaintained

### ISSUE THREAD

**Issue by cbrunnkvist** [cbrunnkvist/ansistrano-symfony-deploy#12]
I will probably not continue working on this until next time I get to do a Symfony project. For now, I have added @gtrias as collaborator _just in case_ so that we can possibly reuse the Travis/Galaxy setup (-and also avoid having to use the `symfony_deploy_playbook_dir` hack). 

 🚧 Apologies for the resulting mess, we will see whether we end up maintaining this or https://github.com/gtrias/ansistrano-symfony-deploy

**Comment by gtrias** [comment]
Well I'm using this in almost all my symfony projects to make them Continuous Deployed. So I'll try to keep it updated. Thanks @cbrunnkvist . Btw, I don't care which of the two repositories should be maintained. Now as I'm collaborator we could just keep yours updated.

**Comment by raul782** [comment]
@cbrunnkvist @gtrias , wouldn't it be great to create the ansymfony project or org, like what capifony did on top of capistrano?
I'm using this  with minor changes on my repo specially for testing with travis. 
https://github.com/raul782/ansistrano-symfony-deploy/commit/ce62066d84a76eaa8e593b62ad5a2efce218bd16

I need to add  coverage for all the 2.x stable versions of symfony but s3 is working now.

**Comment by gtrias** [comment]
Sorry for the late answer.
@raul782 What do you mean with create a project or org?

By the other hand if you are improving the travis testing maybe you could do a pull request when you are finished in order to improve this playbook :)

**Comment by marc-f** [comment]
@gtrias I think he's suggesting a page like capifony.org (ansifony.org?)

@raul782 Any plans for a pull request?

**Comment by FlxPeters** [comment]
Hi,

what do you think about bringing this project to the Ansistrano main project/organisation? Don't know if they are ok with that, but we should ask if it is ok for you.

**Comment by gtrias** [comment]
I think it could be a good thing to have this project together with ansistrano main project. I'm not using ansistrano-symfony ATM so for me is harder to maintain, maybe in the ansistrano project will have more activity. What do you think @cbrunnkvist ?

We should ask to https://github.com/ansistrano staff if they are open to adopt the project.

**Comment by Simperfit** [comment]
@gtrias Did someone ask them if they will agree to add this project to ansistrano ?

**Comment by gtrias** [comment]
@Simperfit not yet. I was waiting for @cbrunnkvist response if he is agree to do this.
I'm going to open an issue to https://github.com/ansistrano/deploy to ask them.

**Comment by ricardclau** [comment]
Hey guys

As I said in the ansistrano deploy issue we don´t have much capacity at the moment to take over more work. In fact we have some PRs that have already been waiting for review for several days :(

If you think adding it to the ansistrano org can improve visibility that´s cool but we are not working with Symfony at the moment either so we cannot promise much dedication to it

**Comment by cbrunnkvist** [comment]
Just to note that I'm following the discussions here but I don't know where to go with it at the moment. 

I don't think there's anything specific about Symfony itself that motivates this being its own project under the ansistrano org, but I have no reservations at all to migrate it there if it would improve maintainability, improve discoverability and so on.

Does anyone know if there are similar ansistrano "extension" projects out there specific to other frameworks? I don't know what to google for really... But if so then perhaps it would be cool to collect all them, again to improve discoverability, under one org.

**Comment by cbrunnkvist** [comment]
The power and flexibility of Ansible playbooks comes from them being either very task specific or very technology specific. I see ansistrano as a very clean and task specific one and it would be wrong to modify it to "know" about any specific framework. What you could do as a nice compromise though, would be to start collecting a set of tech (framework-) specific template playbooks under its `examples/` folder. Maybe that's enough in some/most cases? 

Maybe worth a consideration at least 😄

**Comment by ricardclau** [comment]
At the beginning of ansistrano we thought about creating some symfony specific tasks but then @cbrunnkvist came with his role extending ours and we decided to stay as agnostic as we could

I agree you don´t need to be working on Symfony to maintain this role but if you don´t work on it you may not be aware of some potential new tasks Fabien & co may add to the framework and also the interest in working on it is less strong

We are not aware of any other extension of ansistrano for laravel, drupal or other projects but maybe there are. Are you guys aware of any?

**Comment by gtrias** [comment]
I was searching for other extensions of ansistrano but didn't find anything serious enough :(

By the other hand, about maintainers problem, maybe we may update the README.md exposing the project status and calling for new maintainers who're actually using this playbook to join us.

As far as I know the playbook still works and there aren't breaking changes in symfony deployment process. So the maintenance wouldn't be a great challenge.

**Comment by scuben** [comment]
I am new to ansistrano and ansistrano-symfony. I first just had a look at ansistrano and wanted to give it a try with a symfony project. It worked very nice but I soon discovered that I miss all the symfony related tasks (composer, commands, etc.). I then discovered this repository which also works like a charm. So far I still consider using it for any future project.

But I think some (non technical) points could be addressed to make it easy to start for other beginners to ansistrano(-symfony) like I am/was:

1. integrate this repository into the ansistrano organisation
2. mention this repository in the ansistrano readme
3. create a dedicated website (like capifony)

If I will continue to use ansible for my symfony project deployments I would be able to support the repository as a contributor.

**Comment by gtrias** [comment]
@scuben, thanks for your interest. Actually the official ansistrano readme has a mention to this repository https://github.com/ansistrano/deploy#theyre-talking-about-us. 

I don't see the point of giving ansistrano-symfony a website since ansistrano either doesn't have a full documented one http://ansistrano.com/, just links to github.

Maybe it can be moved to ansistrano org. We talked about with @ricardclau and they are open to adopt it. But it will not receive any support from they part. So maybe what really needs this project is more contributors to move it forward.

> If I will continue to use ansible for my symfony project deployments I would be able to support the repository as a contributor.

This would be nice :)

**Comment by scuben** [comment]
@cbrunnkvist, I now deployed several projects with ansistrano-symfony. Now I tried my first flex based project and run into some problems which I think could be solved with #16.

If it's still okay with you I would be able to step up as a maintainer of this repository. It would be my first try as being a maintainer but hey, this repo seems to be a good fit due to I use it by myself and it does not have that big of a activity.

if you like we can have a chat about what the mission of this repo should be. What should be included and what not. I have some nice organisational ideas already. You'll find me here on github, twitter or the SF Slack channel (https://symfony.com/slack-invite / plandolt).

**Comment by Zokormazo** [comment]
I'm using this role on a regular basis too so It would be great to have an active maintainer

**Comment by cbrunnkvist** [comment]
@scuben it would be great to see it fixed-up by someone who actually uses it 😉 

I have not touched Symfony for more than two years already and I doubt I will in the foreseeable future, so ... yeah.

**Comment by cbrunnkvist** [comment]
I've added @scuben for now - please take a look at the standing PR's and fix/merge as you see fit.

I think it would make sense to transfer the project to reside under the ansistrano org instead of me personally. Is https://github.com/ansistrano owned by @ricardclau ? Just confirm and I'll initiate the transfer.

**Comment by scuben** [comment]
Thank you @cbrunnkvist. I'll have a look at them. Moving the repo to the ansistrano project makes sense.

**Comment by erichard** [comment]
@cbrunnkvist @scuben How can we move forward on this repo ? 

Are you still considering to move the repo or merge the PR ?

**Comment by erichard** [comment]
We are migrating from capistrano to ansible for our Symfony deployments. I have setup a new role with additionals tasks we use : https://github.com/le-phare/ansible-deploy

ansistrano-symfony-deploy will be part of our deployment process so I offer my help here on the maintenance.

**Comment by scuben** [comment]
@erichard I'm glad to hear that! I just merged some PRs and set up a (real) CI on travis.

I still would like to move the Repo to the ansistrano organisation, but that will be at a later time.
With the PR merged for removing the deprecated `include:` we bump the minimum required ansible version to 2.4 for that I'll create a new minor version.

Any help in PR is very much appreciated. I'll close this issue for now and will create a new one with the moving of the Repository at a later time.
