### ISSUE TITLE
FIX Permissions

### ISSUE THREAD

**Issue by malutanpetronel** [cbrunnkvist/ansistrano-symfony-deploy#27]
In the capistrano I was having some writable folders and permission settings
..
  run "sudo chown -R #{user}:#{webserver_user} #{deploy_to}"
  run "sudo chown -RH root:www-data #{latest_release}/#{cache_path}"
..
Is there anything included here?

**Comment by scuben** [comment]
You can use the hooks to run additional tasks. In those you are free to run anything you like including some permission changes.

**Comment by piotrkochan** [comment]
@scuben it is impossible to use the hooks because they are already overriden by ansistrano-symfony-deploy

**Comment by scuben** [comment]
@piotrkochan Only two are used by this library. But in additional we also provide hooks to hook into the process. See https://github.com/cbrunnkvist/ansistrano-symfony-deploy/blob/master/config/after_symlink_shared.yml
