### ISSUE TITLE
composer self-update non stable version

### ISSUE THREAD

**Issue by revilon1991** [cbrunnkvist/ansistrano-symfony-deploy#30]
Hello.
I'm deploy my project and get error
`Problem 1
    - ocramius/package-versions is locked to version 1.4.2 and an update of this package was not requested.
    - ocramius/package-versions 1.4.2 requires composer-plugin-api ^1.0.0 -> found composer-plugin-api[2.0.0] but it does not match your constraint.
  Problem 2
    - symfony/flex is locked to version v1.4.8 and an update of this package was not requested.
    - symfony/flex v1.4.8 requires composer-plugin-api ^1.0 -> found composer-plugin-api[2.0.0] but it does not match your constraint.
  Problem 3
    - ocramius/package-versions 1.4.2 requires composer-plugin-api ^1.0.0 -> found composer-plugin-api[2.0.0] but it does not match your constraint.
    - jean85/pretty-package-versions 1.2 requires ocramius/package-versions ^1.2.0 -> satisfiable by ocramius/package-versions[1.4.2].
    - jean85/pretty-package-versions is locked to version 1.2 and an update of this package was not requested.`

It's because composer have version
Composer version 2.0-dev (2.0-dev+d34ea60c488ad62e7944eac3d3e768b449ae767a) 2020-04-07 11:09:22

**jean85/pretty-package-versions 1.4.2** can't work with **composer-plugin-api 2.0.0**

I'm try remove composer.phar, but deploy instruction still download dev version composer

How configure download version composer?

**Comment by scuben** [comment]
Possible solution working on: https://github.com/cbrunnkvist/ansistrano-symfony-deploy/pull/31

**Comment by bcodp** [comment]
@scuben it may be a good idea to have a variable to specify a composer version and by default to download the stable version no ?

**Comment by scuben** [comment]
Problem is solved with the newest released version 1.4.0.

@bcodp yes that sounds like a good idea. Can you create a PR?
