### ISSUE TITLE
Set webuser (apache,nginx) rights to app/cache folder

### ISSUE THREAD

**Issue by markitosgv** [cbrunnkvist/ansistrano-symfony-deploy#7]
Hi,

When you deploy a new release, app/cache folder have yourappuser rights, often webuser (apache) needs to create/modify cache files.

I think is necessary set apache user rights over cache folder like:

``` bash
cd {{ ansistrano_release_path.stdout }} && setfacl -R -m u:apache:rwX -m u:eplanning:rwX app/cache
cd {{ ansistrano_release_path.stdout }} && setfacl -dR -m u:apache:rwX -m u:eplanning:rwX app/cache
```

What do you think?

**Comment by alfonsomga** [comment]
@cbrunnkvist are you planning to add this to the role? this step is fundamental.

**Comment by cbrunnkvist** [comment]
I think you need to add this step by yourself in a preceding or following step..? It might be quite specific to each environment and I'm not sure about what could be good default values.

**Comment by weaverryan** [comment]
If you're using Symfony 3.3 or higher (and maybe earlier, not sure), the `var/cache` directory does NOT need to be writable. Just run `cache:warmup` (or `cache:clear`, which does warmup in Symfony 3) and make sure you have apcu or opcache installed on your server. Then, nothing needs to be written to the cache after deploy. And everyone wins :)

**Comment by Zokormazo** [comment]
You can use #19 to add custom tasks before or after any step

**Comment by Zokormazo** [comment]
Now that #19 is merged it's possible to add custom steps to change owner & permission after deployment

**Comment by scuben** [comment]
@markitosgv I just tagged the new release v1.2.0 with that you'll be able to use the hook system to change the permissions.
